version: '3.3'

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    ports:
      # set a different exposed port number (9140) for each host
      - "9140:9100"
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'